const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirti",
      category: "Shirts",
      image: " /images/1.png",
      price: 120,
      countlnStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas Slim shirt",
      slug: "adidas—slim-shirti",
      category: "Shirts",
      image: " /images/2.png",
      price: 120,
      countlnStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Solo Slim shirt",
      slug: "solo—slim-shirti",
      category: "Shirts",
      image: " /images/3.png",
      price: 120,
      countlnStock: 10,
      brand: "Solo",
      rating: 4.0,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Puma Slim shirt",
      slug: "puma—slim-shirti",
      category: "Shirts",
      image: " /images/4.png",
      price: 120,
      countlnStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};

export default data;
